language: node_js
sudo: false

node_js:
    - "0.10"
    - "0.12"
    - "iojs"
    - "iojs-v1"
    - "iojs-v2"
    - "4"
    - "5"

cache:
  directories:
    - node_modules
after_script:
  - npm run coverage